server.port: 9001
spring.graphql.graphiql:
  enabled: true
  path: /graphiql
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql.init.mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
